# Generated by Django 6.0.8 on 2026-08-24 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0002_productembedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSearchImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=2000)),
                ('source', models.CharField(choices=[('GROQ', 'Groq'), ('FALLBACK', 'ORM fallback')], max_length=12)),
                ('position', models.PositiveSmallIntegerField()),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_search_impressions', to='merchants.merchant')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_search_impressions', to='merchants.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='analytics_a_merchan_fc69e2_idx'), models.Index(fields=['product', 'created_at'], name='analytics_a_product_c75b94_idx')],
            },
        ),
        migrations.CreateModel(
            name='LostOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=2000)),
                ('reason', models.CharField(choices=[('PRICE', 'Price above buyer budget'), ('STOCK', 'Product out of stock')], max_length=12)),
                ('requested_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_opportunities', to='merchants.merchant')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_opportunities', to='merchants.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'reason', 'created_at'], name='analytics_l_merchan_6fcf07_idx'), models.Index(fields=['product', 'created_at'], name='analytics_l_product_26f2c0_idx')],
            },
        ),
    ]
