# Generated by Django 6.0.8 on 2026-08-24 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0003_merchant_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_request", models.TextField(max_length=2000)),
                ("parsed_constraints", models.JSONField(default=dict)),
                ("catalog_candidate_ids", models.JSONField(default=list)),
                (
                    "provider_source",
                    models.CharField(
                        choices=[
                            ("GROQ", "Groq"),
                            ("FALLBACK", "Deterministic fallback"),
                        ],
                        max_length=12,
                    ),
                ),
                ("decision_summary", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationDecision",
            fields=[
                (
                    "decision_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("explanation", models.TextField(max_length=2000)),
                ("trade_offs", models.JSONField(default=list)),
                ("catalog_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_decisions",
                        to="merchants.product",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="agents.agentsession",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "product"),
                        name="unique_session_product_decision",
                    )
                ],
            },
        ),
    ]
