# Generated by Django 6.0.8 on 2026-08-24 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("merchants", "0004_productrelationship"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowthOffer",
            fields=[
                (
                    "offer_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("explanation", models.CharField(max_length=800)),
                ("trade_off", models.CharField(blank=True, max_length=500)),
                (
                    "incremental_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("is_synthetic", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "addon_decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_offer",
                        to="agents.recommendationdecision",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_offer_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_growth_offers",
                        to="agents.recommendationdecision",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_offers",
                        to="merchants.product",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_offers",
                        to="merchants.productrelationship",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_offers",
                        to="agents.agentsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "response", "is_synthetic"],
                        name="agents_grow_product_838c14_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "primary_decision", "product"),
                        name="unique_session_growth_offer",
                    )
                ],
            },
        ),
    ]
