# Generated by Django 6.0.8 on 2026-08-23 15:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='merchants.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTransactionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_thought_summary', models.TextField()),
                ('conversion_status', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('PURCHASED', 'Purchased'), ('REJECTED', 'Rejected')], db_index=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_transaction_audits', to='merchants.merchant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_audits', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', 'status'], name='orders_orde_product_fd7edb_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenttransactionaudit',
            constraint=models.UniqueConstraint(fields=('order', 'conversion_status'), name='unique_order_conversion_audit'),
        ),
    ]
