# Generated by Django 6.0.8 on 2026-08-24 14:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_order_lines(apps, schema_editor):
    Cart = apps.get_model("orders", "Cart")
    CartItem = apps.get_model("orders", "CartItem")
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    Quote = apps.get_model("orders", "Quote")
    QuoteItem = apps.get_model("orders", "QuoteItem")

    for quote in Quote.objects.select_related("product__merchant", "decision").all().iterator():
        if not quote.product_id or not quote.decision_id:
            continue
        cart_status = "EXPIRED" if quote.status == "EXPIRED" else "QUOTED"
        cart = Cart.objects.create(
            buyer_id=quote.buyer_id,
            session_id=quote.session_id,
            status=cart_status,
        )
        CartItem.objects.create(
            cart_id=cart.pk,
            decision_id=quote.decision_id,
            product_id=quote.product_id,
            quantity=quote.quantity,
        )
        QuoteItem.objects.create(
            quote_id=quote.pk,
            decision_id=quote.decision_id,
            product_id=quote.product_id,
            merchant_id=quote.product.merchant_id,
            product_title=quote.product.title,
            merchant_name=quote.product.merchant.name,
            quantity=quote.quantity,
            unit_price=quote.unit_price,
            line_total=quote.total_amount,
            explanation=quote.decision.explanation,
            trade_offs=quote.decision.trade_offs,
        )
        quote.cart_id = cart.pk
        quote.save(update_fields=["cart"])

    status_map = {
        "PENDING": "PAYMENT_FAILED",
        "FAILED": "PAYMENT_FAILED",
        "PAID": "PAID",
        "CANCELLED": "CANCELLED",
    }
    for order in Order.objects.select_related("product__merchant").all().iterator():
        if order.product_id and order.quantity:
            unit_price = order.total_amount / order.quantity
            OrderItem.objects.create(
                order_id=order.pk,
                product_id=order.product_id,
                merchant_id=order.product.merchant_id,
                product_title=order.product.title,
                merchant_name=order.product.merchant.name,
                unit_price=unit_price,
                quantity=order.quantity,
                line_total=order.total_amount,
            )
        order.status = status_map.get(order.status, "PAYMENT_FAILED")
        if order.status == "PAID":
            order.paid_at = order.updated_at
        order.save(update_fields=["status", "paid_at"])


def reverse_legacy_statuses(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.all().iterator():
        if order.status == "PAID":
            legacy_status = "PAID"
        elif order.status == "CANCELLED":
            legacy_status = "CANCELLED"
        elif order.status == "PAYMENT_PENDING":
            legacy_status = "PENDING"
        else:
            legacy_status = "FAILED"
        Order.objects.filter(pk=order.pk).update(status=legacy_status)


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("merchants", "0003_merchant_owner"),
        ("orders", "0003_approvalgrant_quote_moneyactionaudit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "cart_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("QUOTED", "Quoted"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("QUOTE_APPROVAL", "Quote approval"),
                            ("PAYMENT_ORDER", "Payment order"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField(default=201)),
                ("error_code", models.CharField(blank=True, max_length=48)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=255)),
                ("merchant_name", models.CharField(max_length=200)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=255)),
                ("merchant_name", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("explanation", models.TextField(blank=True, max_length=2000)),
                ("trade_offs", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "reservation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CONSUMED", "Consumed"),
                            ("RELEASED", "Released"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="agenttransactionaudit",
            name="unique_order_conversion_audit",
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="reservation_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="reservation_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="state_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="moneyactionaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("QUOTE_ALLOWED", "Quote allowed"),
                    ("MONEY_BLOCKED", "Money action blocked"),
                    ("APPROVAL_GRANTED", "Approval granted"),
                    ("APPROVAL_CONSUMED", "Approval consumed"),
                    ("ORDER_CREATED", "Order created"),
                    ("PAYMENT_CAPTURED", "Payment captured"),
                    ("PAYMENT_FAILED", "Payment failed"),
                    ("RESERVATION_CREATED", "Reservation created"),
                    ("RESERVATION_RELEASED", "Reservation released"),
                    ("RESERVATION_CONSUMED", "Reservation consumed"),
                    ("ORDER_CANCELLED", "Order cancelled"),
                    ("ORDER_EXPIRED", "Order expired"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="merchants.product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("QUOTED", "Quoted"),
                    ("APPROVED", "Approved"),
                    ("PAYMENT_PENDING", "Payment pending"),
                    ("PAID", "Paid"),
                    ("PAYMENT_FAILED", "Payment failed"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                    ("REFUND_PENDING", "Refund pending"),
                    ("REFUNDED", "Refunded"),
                ],
                db_index=True,
                default="PAYMENT_PENDING",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="agents.recommendationdecision",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="merchants.product",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["buyer", "status"], name="orders_orde_buyer_i_4389c9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agenttransactionaudit",
            constraint=models.UniqueConstraint(
                fields=("order", "merchant", "conversion_status"),
                name="unique_order_conversion_audit",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="agents.agentsession",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="cart",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote",
                to="orders.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items",
                to="agents.recommendationdecision",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items",
                to="merchants.product",
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="idempotency_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="idempotency_records",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="idempotency_records",
                to="orders.quote",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="merchants.merchant",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="merchants.product",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_items",
                to="agents.recommendationdecision",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_items",
                to="merchants.merchant",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_items",
                to="merchants.product",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.quote",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_reservations",
                to="merchants.product",
            ),
        ),
        migrations.RunPython(backfill_legacy_order_lines, reverse_legacy_statuses),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"), name="unique_cart_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("buyer", "operation", "key"), name="unique_buyer_operation_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="unique_order_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="order_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_total__gte", 0)),
                name="order_item_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteitem",
            constraint=models.UniqueConstraint(
                fields=("quote", "product"), name="unique_quote_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="quote_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_total__gte", 0)),
                name="quote_item_total_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["status", "expires_at"], name="orders_stoc_status_e8aa04_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="unique_order_product_reservation"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="reservation_quantity_positive",
            ),
        ),
    ]
