# Generated by Django 6.0.8 on 2026-08-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_growthoffer"),
        ("orders", "0005_cartitem_growth_offer_orderitem_growth_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="growth_offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items",
                to="agents.growthoffer",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="growth_offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="agents.growthoffer",
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="growth_offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_items",
                to="agents.growthoffer",
            ),
        ),
    ]
