# Generated by Django 6.0.8 on 2026-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_cartitem_growth_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idempotencyrecord",
            name="operation",
            field=models.CharField(
                choices=[
                    ("COMMERCE_QUOTE", "Commerce quote"),
                    ("QUOTE_APPROVAL", "Quote approval"),
                    ("PAYMENT_ORDER", "Payment order"),
                ],
                max_length=20,
            ),
        ),
    ]
