# Generated by Django 6.0.8 on 2026-08-25 04:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_idempotencyrecord_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
        migrations.AlterField(
            model_name='moneyactionaudit',
            name='action',
            field=models.CharField(choices=[('QUOTE_ALLOWED', 'Quote allowed'), ('MONEY_BLOCKED', 'Money action blocked'), ('APPROVAL_GRANTED', 'Approval granted'), ('APPROVAL_CONSUMED', 'Approval consumed'), ('ORDER_CREATED', 'Order created'), ('PAYMENT_CAPTURED', 'Payment captured'), ('PAYMENT_FAILED', 'Payment failed'), ('RESERVATION_CREATED', 'Reservation created'), ('RESERVATION_RELEASED', 'Reservation released'), ('RESERVATION_CONSUMED', 'Reservation consumed'), ('ORDER_CANCELLED', 'Order cancelled'), ('ORDER_EXPIRED', 'Order expired'), ('PAYMENT_AUTHORIZED', 'Payment authorized'), ('REFUND_INITIATED', 'Refund initiated'), ('REFUND_PROCESSED', 'Refund processed'), ('REFUND_FAILED', 'Refund failed'), ('RECONCILED', 'Reconciled'), ('MANUAL_REVIEW', 'Manual review')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='moneyactionaudit',
            name='outcome',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('QUOTED', 'Quoted'), ('APPROVED', 'Approved'), ('PAYMENT_PENDING', 'Payment pending'), ('PAID', 'Paid'), ('PAYMENT_FAILED', 'Payment failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded'), ('MANUAL_REVIEW', 'Manual review')], db_index=True, default='PAYMENT_PENDING', max_length=24),
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('reason_code', models.CharField(max_length=48)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('requested_by', models.CharField(default='OPERATOR', max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('order',), name='one_pending_refund_per_order')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('exception_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(db_index=True, max_length=48)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_exceptions', to='orders.order')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('order', 'reason_code'), name='one_open_reconciliation_exception')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_event_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('deduplication_key', models.CharField(max_length=80, unique=True)),
                ('event_type', models.CharField(db_index=True, default='UNKNOWN', max_length=64)),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('signature_verified', models.BooleanField(db_index=True, default=False)),
                ('processing_state', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=12)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=48)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='orders.order')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['processing_state', 'received_at'], name='orders_webh_process_d37944_idx')],
            },
        ),
    ]
