# Generated by Django 6.0.8 on 2026-08-24 10:10

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def setup_optional_vector_index(apps, schema_editor):
    from apps.merchants.vector_setup import setup_vector_index

    setup_vector_index(schema_editor.connection.alias)


def remove_optional_vector_index(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS merchants_product_embedding")


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='semantic_index', serialize=False, to='merchants.product')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'merchants_product_embedding',
                'managed': False,
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='merchants_p_price_f3853c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category', 'price'], name='merchants_p_is_acti_5cd1ee_idx'),
        ),
        migrations.RunPython(setup_optional_vector_index, remove_optional_vector_index),
    ]
