# Generated by Django 6.0.8 on 2026-08-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0003_merchant_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("ACCESSORY", "Accessory"),
                            ("COMPLEMENT", "Complement"),
                            ("SUBSTITUTE", "Substitute"),
                            ("BUNDLE", "Bundle"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("compatibility", models.JSONField(default=dict)),
                ("benefit", models.CharField(max_length=500)),
                ("trade_off", models.CharField(blank=True, max_length=500)),
                ("offer_label", models.CharField(blank=True, max_length=120)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="merchants.product",
                    ),
                ),
                (
                    "source_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="merchants.product",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["source_product", "is_active", "priority"],
                        name="merchants_p_source__86c131_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_product",
                            "related_product",
                            "relationship_type",
                        ),
                        name="unique_product_relationship",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_product", models.F("related_product")),
                            _negated=True,
                        ),
                        name="relationship_products_differ",
                    ),
                ],
            },
        ),
    ]
