# Generated by Django 6.0.8 on 2026-08-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0004_productrelationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="source_license",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="source_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="source_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
